### ISSUE TITLE
Live Events don't open any games.

### ISSUE THREAD

**Issue by PTF94** [tekbec/plugin.video.nhl66#5] opened 2024-10-10 14:19 UTC
Whenever I try to open a live event to pick a stream, it brings up an error that says "NoneType".

Replays are working fine.

**Comment by tekbec** [comment] 2024-10-10 21:22
Probably has something to do with the new team in Utah being not recognized. Let me push an update and see if it's still there.

Edit: Seems to be working for me using v1.0.8, if it's still not working, please send a copy of your log file.

**Comment by PTF94** [comment] 2024-10-11 15:20
I'm using it on Android TV with 1.0.8 downloaded from the official repository. Yesterday I tried to open a live game (STL @ SJS), but it started playing from the beginning of the broadcast instead of being live. I will see today if the same issue occurs.

**Comment by tekbec** [comment] 2024-10-11 16:05
Were you using an NHL.TV stream or ESPN? Had the same issue yesterday using NHL.TV but no issue with ESPN. inputstream seems to have difficulties parsing NHL.TV live streams manifest. Will try to see what can be done tonight.

**Comment by PTF94** [comment] 2024-10-11 23:21
Yesterday I was using NHL.tv streams as I don't have a premium account.

**Comment by tekbec** [comment] 2024-10-11 23:40
Just released an update (v1.0.9), can you try it and see if you still have the issue?

**Comment by PTF94** [comment] 2024-10-12 00:45
Unfortunately the issue of starting at the beginning of the broadcast instead of being Live still persists.

**Comment by tekbec** [comment] 2024-10-12 00:49
Been able to reproduce it on my android tv as well. I'll try something else and release a new version soon.

**Comment by tekbec** [comment] 2024-10-12 02:56
Just released v1.0.10 which will hopefully fix your issue. Let me know!

**Comment by Sumoallstar** [comment] 2024-10-12 15:41
Was having the same issue with NHL.TV streams on Nvidia Shield.  v1.0.10 has corrected it. Thanks for all your work!

**Comment by PTF94** [comment] 2024-10-12 23:19
Tested the new version on PC and both Live events and Replays seem to be working fine now. I will test on Android TV later. Huge thanks, @tekbec !

**Comment by tekbec** [comment] 2024-10-13 18:33
Glad to hear it, I'll wait for your feedback before marking it as completed.

**Closed as completed** 2024-10-16 17:42 UTC

**Comment by PTF94** [comment] 2024-10-17 16:05
On Android TV games are opening now. Huge thanks.
